### ISSUE TITLE
tp-1 ver estructura

### ISSUE THREAD

**Issue by SergioMartellotti** [ScheffelaarGerman/EstrD2024s2#3]
tanto la carpeta como el archivo van sin mayúsculas (todo minúsculas)

**Comment by ScheffelaarGerman** [comment]
Buenos dia Sergio. Ahora lo modifico. no pude subir el repositorio mediante el pushh lo hice manualmente esta vez. voy a pedirle a un companero que me explique como hacerlo manana en clase

**Comment by SergioMartellotti** [comment]
Ok, no hay problema, fijate que compile el archivo. Sino no puedo corregir.
