### ISSUE TITLE
tp-1 no compila el archivo

### ISSUE THREAD

**Issue by SergioMartellotti** [ScheffelaarGerman/EstrD2024s2#4]
Si no compila no puedo probarlo.

**Comment by ScheffelaarGerman** [comment]
Ahi lo volvi a subir Sergio. Realmente estuve intentando desde el martes subirlo con el metodo que explicaron pero no pude. Hay problema de que se suban manualmente ?

**Comment by ScheffelaarGerman** [comment]
Sergio yo lo cargo en winhugstipeo :r y me complia.
A eso te haces referencia? como veras son mis primeros pasos jajajaj

**Comment by SergioMartellotti** [comment]
Tranqui. Si, exactamente a eso me refiero. Igual acabo de descargarlo nuevamente para probarlo y decirte en que linea me daba error pero anduvo bien. Ya mismo te corrijo.
