### ISSUE TITLE
tp-1 ver implica, yTambien y oBien

### ISSUE THREAD

**Issue by SergioMartellotti** [ScheffelaarGerman/EstrD2024s2#5]
En los tres ejercicios estás teniendo el mismo problema así que solo voy a hablar de uno.

yTambien True True = True es doble Pattern Matching, solo podes ver un dato por caso.
En el 2do caso no van y no está permitido dos comodines "_ _".

Por ejemplo:
oBien podría ser algo así como
oBien True _ = True
oBien _ b = b

De esta manera yo se que si en el primer booleano hay un true (no me importa mirar el 2do porque ya se que es true) entonces devuelvo directamente true.
Si es False, entraría en el 2do caso, y usando una variable veo que si es true devuelvo true y si es false devuelvo false.
implica e yTambien te quedan para hacer a vos... pero la estructura debería ser similar a esta.

**Comment by SergioMartellotti** [comment]
Seguis haciendo doble PM en implica e yTambien porque en ambos estás mirando dos valores en el primer caso, aún poniendo una variable.

Por eso te decía que la solución es como la dada en oBien, donde en el primer caso miras solo el 1er valor (y un comodín en el segundo valor) y en el segundo caso empezas poniendo un comodín y trabajas sobre el 2do valor. Para evitar el doble PM.

**Comment by ScheffelaarGerman** [comment]
Buenas tardes Sergio. Ahi arregle lo que faltaba, me estoy familiarizándome con este entorno nose si te tengo que avisar de esta manera. Gracias. Saludos

**Comment by SergioMartellotti** [comment]
No, no tenes que avisarme. Lo que si deberías es averiguar como ponerle "título" al push. Como para al momento de pushear poner "resuelvo issue #5" y ahí me avisaría directamente que resolviste por email.

Perfecto Germán quedaron impecables las soluciones. De todos modos me corrijo porque te dije algo mal. 

"Seguís haciendo doble PM en implica e yTambien porque en ambos estás mirando dos valores en el primer caso, aún poniendo una variable." Esto está mal. No es doble PM. Lo habías hecho bien, mala mía. Perdón.

" En el 2do caso no van y no está permitido dos comodines "_ _". " Esto también es Falso. Si se puede dejar un caso con comodines siempre y cuando sea el último.
